translate comments into chinese
rust-lang-cn/nomicon-zh-Hans pull request #8
Opened 2021-09-28 00:52 UTC by hsqStephenZhang

将一些注释翻译成了中文

2021-09-28 05:19 UTC, PureWhiteWu commented
1. CI 挂了，需要修一下
2. 英文/数字和中文之间需要有空格，参考我的翻译格式

2021-09-28 09:10 UTC, hsqStephenZhang commented
okok, i will fix it

2021-09-28 09:12 UTC, hsqStephenZhang commented
哪些地方需要用 `` 标注起来呢

2021-09-28 09:54 UTC, PureWhiteWu commented
> 哪些地方需要用 `` 标注起来呢

和原文保持一致？

2021-09-28 10:37 UTC, PureWhiteWu requested changes
大致看了一下，还有些问题 comment 了，下面没有一个一个评论的也有这些问题，你可以再自己检查一下。

2021-09-28 10:37 UTC, PureWhiteWu commented on src/aliasing.md
> +    let cached_input = *input; // 将 `*input` 中的内容保存在寄存器中
不要在末尾有额外的空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/aliasing.md
> +    *output = 1;    // 同时覆写了 input 引用的内容，因为它们实际上引用了同一块内存
覆写 -> 覆盖 是不是好些？

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-base.md
> +        // 当前的指针就是第一个引用，因此初始时设置 count=1
`设置 count 为 1`或者`设置 count = 1`

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-base.md
> +        // 当前的指针就是第一个引用，因此初始时设置 count=1
同上

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-final.md
> +        // 当前的指针就是第一个引用，因此初始时设置 count=1
同上

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-final.md
> +            // 我们从 Box::into_raw 得到该指针，因此使用 `.unwrap()` 是完全OK的
OK 左右两边加空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-final.md
> +        // 使用 relax 这种排序方式也就完全可行.
使用中文句号

2021-09-28 10:37 UTC, PureWhiteWu commented on src/arc-mutex/arc-final.md
> +        // 因此使用 fence 来进行保护是非常有必要.
同上

2021-09-28 10:37 UTC, PureWhiteWu commented on src/atomics.md
> +    // 尝试将原子变量设置为true，以此来获得锁
true 左边加空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/checked-uninit.md
> +        // 所以x不需要是可变的
x 左右加空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/checked-uninit.md
> +// 所以一旦运行到这里,x 一定已经初始化了
使用中文逗号

2021-09-28 10:37 UTC, PureWhiteWu commented on src/destructors.md
> +            // 需要将 box 字段设置为 None,防止 Rust 对 box 成员可能存在的drop操作
使用中文逗号，drop 左右加空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/drop-flags.md
> +let mut x = Box::new(0); // let 创建了一个全新的变量，所以一定(也没有必要)调用 drop
删除行末多余空格

2021-09-28 10:37 UTC, PureWhiteWu commented on src/drop-flags.md
> +                            // 检查 drop 标志位!
使用中文感叹号

2021-09-28 10:38 UTC, PureWhiteWu commented
可以参考 https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7/%E4%B8%AD%E8%8B%B1%E6%96%87%E6%B7%B7%E7%94%A8%E6%97%B6%E6%A0%87%E7%82%B9%E7%94%A8%E6%B3%95.html

2021-10-06 02:11 UTC, PureWhiteWu requested changes
赞！
还有最后一点小问题，修完就好啦！

2021-10-06 02:11 UTC, PureWhiteWu commented on .vscode/settings.json
> +{
这个文件是不是应该删掉？

2021-10-06 02:11 UTC, PureWhiteWu commented on src/arc-mutex/arc-base.md
> +
这里应该不要空行，是 mdbook 的标记，会影响渲染的吧？
下同

2021-10-06 02:11 UTC, PureWhiteWu commented on src/ffi.md
> +  cb(cb_target, 7); // 这会调用 Rust 代码中的 callback (&rustObject, 7)
callback 后不需要空格

2021-10-06 02:11 UTC, PureWhiteWu commented on src/ownership.md
> +    // (这在 Rust 中不会编译通过)
这个括号应该改成中文括号，下同

2021-10-06 02:12 UTC, PureWhiteWu commented on src/what-unsafe-does.md
> +
这里不需要空行吧？下同

2021-10-06 05:19 UTC, PureWhiteWu commented
另外，还有个 conflict 需要解决下

2021-10-06 10:43 UTC, hsqStephenZhang commented on .vscode/settings.json
> +{
sorry，忘记从git里面删掉了

2021-10-06 12:55 UTC, hsqStephenZhang commented on src/what-unsafe-does.md
> +
似乎是vscode自动给我格式化了2333

2021-10-06 12:55 UTC, hsqStephenZhang commented on src/what-unsafe-does.md
> +
似乎是vscode自动给我格式化了2333

2021-10-07 04:37 UTC, PureWhiteWu commented
CI 挂了，看下什么原因？

2021-10-08 02:35 UTC, PureWhiteWu approved these changes

2021-10-08 02:35 UTC, merged